name: Terraform GitHub Repo Automation

on:
  workflow_dispatch:
    inputs:
      tf_action:
        required: true
        default: "apply"
        type: choice 
        options: 
        - apply 
        - destroy
        
permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        if: ${{ github.event.inputs.tf_action == 'apply' }}
        env:
          TF_VAR_github_token: ${{ secrets.PAT }}
        run: terraform apply -auto-approve

      - name: Terraform destroy
        if: ${{ github.event.inputs.tf_action == 'destroy' }}
        env:
          TF_VAR_github_token: ${{ secrets.PAT }}
        run: terraform destroy -auto-approve
